services:
  - type: web
    name: Teamsync
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci --prefer-offline
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
