version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    command: --replSet rs0 --bind_ip_all
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: --replSet rs0 --bind_ip_all
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: --replSet rs0 --bind_ip_all
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
